const suggestions = [
  'O que é HTML5?',
  'O que é CSS#?',
  'O que é Javascript?',
  'Como aprender a programar?',
  'Como aprender a programar em Javascript?',
  'Como aprender a programar em Pyton?',
  'O que é HTML?',
  'O que é CSS?',
  'Cascading Style Sheet',
  'Folha de estilo em cascata',
  'How to learn English in one week?',
  'Red Dead Redemption 2',
  'Detonado',
  'Brasil',
  'Bandeira',
  'Flamengo',
  'Vasco',
  'Como aprender inglês?',
  'Como aprender espanhol?',
  'Hello world?',
  'Lógica',
  'Lógica de programação',
  'Expressões',
  'Expressões matemáticas',
  'Expressões regulares',
  'Youtube',
  'Yahoo',
  'Yahoo parque aquático',
  'Udemy',
  'Netflix',
  'Rockeatseat',
  'NepalCoding',
  'Abordagem divertida',
  'Programação orientada a objetos!',
  'Casimiro',
  'Cazé',
  'Louro José',
  'Uchiha Itachi',
  'Vallorant',
  'Fortnite',
  'Point blank',
  'Regex',
  'Programação procedural',
  'Orientação a objetos',
  'Object first',
  'Coca-cola',
  'Pepsi',
  'Acerola',
  'Docker',
  'Pink floyd',
  'Jesus',
  'Jesus Cristo',
  'Deus'
]
