const suggestions = [
  'O que é HTML5?',
  'O que é CSS#?',
  'O que é Javascript?',
  'Como aprender a programar?',
  'Como aprender a programar em Javascript?',
  'Como aprender a programar em Pyton?',
  'Como aprender inglês?',
  'Como aprender espanhol?',
  'Hello world?',
  'Lógica',
  'Lógica de programação',
  'Expressões',
  'Expressões matemáticas',
  'Expressões regulares',
  'Youtube',
  'Yahoo',
  'Yahoo parque aquático',
  'Udemy',
  'Netflix',
  'Rockeatseat',
  'NepalCoding',
  'Abordagem divertida',
  'Programação orientada a objetos!'
]
